import type { Metadata } from "next";
import { Geist, Geist_Mono, Overpass } from "next/font/google";
import "./globals.css";

const overpass = Overpass({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Interactive rating",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overpass.className} text-[15px] text-neutral-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
